backend:
  name: test-repo

publish_mode: editorial_workflow

media_folder: static/assets

collections:
  - name: post
    label: Posts
    folder: src/posts
    create: true
    slug: {{slug}}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}