backend:
  name: github
  branch: master
  repo: ezeikel/ezeikel-portfolio-web

media_folder: static/assets
public_folder: /assets

collections:
  - name: "post"
    label: "Post"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}